CREATE TABLE STINLOT.COM 
(
  NUMCOM NUMBER(20) NOT NULL 
, NUMCLI NUMBER(20) NOT NULL 
, FRAISPORT NUMBER(10) 
, ANCOM NUMBER(10) 
, PAYEMENT VARCHAR2(20) 
, CONSTRAINT COM_PK PRIMARY KEY 
  (
    NUMCOM 
  )
  ENABLE 
);