CREATE TABLE STINLOT.FOU 
(
  NUMFOU NUMBER(20) NOT NULL 
, NOMFOU VARCHAR2(30) NOT NULL 
, PAYS VARCHAR2(20) NOT NULL 
, TEL NUMBER(10) NOT NULL 
, CONSTRAINT FOU_PK PRIMARY KEY 
  (
    NUMFOU 
  )
  ENABLE 
);