CREATE TABLE STINLOT.PRO 
(
  NUMPRO NUMBER(20) NOT NULL 
, PRIXUNIT NUMBER(10) NOT NULL 
, NUMFOU NUMBER(20) NOT NULL 
, NOMPRO VARCHAR2(20) NOT NULL 
, TYPEPRO VARCHAR2(20) NOT NULL 
, CONSTRAINT PRO_PK PRIMARY KEY 
  (
    NUMPRO 
  )
  ENABLE 
);
