CREATE TABLE VOL 
(
  IDVOL NUMBER(8) NOT NULL 
, DATE_HEURE_DEPART DATE NOT NULL 
, DATE_HEURE_ARRIVEE DATE NOT NULL 
, VILLE_DEPART VARCHAR2(20) NOT NULL 
, VILLE_ARRIVEE VARCHAR2(20) NOT NULL 
, CONSTRAINT TABLE1_PK PRIMARY KEY 
  (
    IDVOL 
  )
  ENABLE 
);
