CREATE TABLE PILOTE 
(
  MATRICULE VARCHAR2(20) NOT NULL 
, NOM VARCHAR2(20) NOT NULL 
, VILLE VARCHAR2(20) NOT NULL 
, AGE NUMBER(3) NOT NULL 
, SALAIRE NUMBER(10) NOT NULL 
, CONSTRAINT PILOTE_PK PRIMARY KEY 
  (
    MATRICULE 
  )
  ENABLE 
);
